### ISSUE TITLE
Close notification manually

### ISSUE THREAD

**Issue by Vouivre** [muevoid/Wayherb#7]
Hi,

I'm testing wayherb and I send some notification with the following command:

    echo "My notification" | xargs wayherb

To close the notification, I have to click on it. If there is a timeout, apparently it doesn't work.

Did I miss something in the configuration ? 

EDIT: Sorry, I think I have to use the git version.

**Comment by Vouivre** [comment]
It was the solution, sorry about the issue.

**Comment by muevoid** [comment]
Glad you figured it out!

**Comment by muevoid** [comment]
The version that didnt work was it packaged on a distro? The github releases here are probably outdated

**Comment by Vouivre** [comment]
> The version that didnt work was it packaged on a distro? The github releases here are probably outdated

I had a look on repology, and it seems no distribution packaged `wayherb`. I will test your software, but I can imagine kisslinux will be the first distro to package `wayherb`. I'm not really interested by the other notification systems. Thank you for porting `herbe` to wayland :+1:!!!
